#!/usr/bin/env python3
"""Patch Project Aloha 2412.74 to power T860 SD rails and signal SD detection."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


def replace_once(data: bytes, old: bytes, new: bytes, label: str) -> bytes:
    count = data.count(old)
    if count != 1:
        raise SystemExit(f"error: {label} marker count is {count}, expected 1")
    return data.replace(old, new, 1)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source_root", type=Path)
    parser.add_argument("--report", required=True, type=Path)
    args = parser.parse_args()

    root = args.source_root.resolve()
    source = root / "Common/MU/PcBdsPkg/MsBootPolicy/MsBootPolicy.c"
    inf = root / "Common/MU/PcBdsPkg/MsBootPolicy/MsBootPolicy.inf"
    t860_sdcc = (
        root
        / "Platforms/SurfaceDuo1Pkg/Device/samsung-gts6lwifi/Binaries/QcomPkg/Drivers/SdccDxe/SdccDxe.efi"
    )
    mtp_sdcc = (
        root
        / "Platforms/SurfaceDuo1Pkg/Device/qcom-mtp8150/Binaries/QcomPkg/Drivers/SdccDxe/SdccDxe.efi"
    )
    t860_depex = t860_sdcc.with_suffix(".depex")
    mtp_depex = mtp_sdcc.with_suffix(".depex")
    for path in (source, inf, t860_sdcc, mtp_sdcc, t860_depex, mtp_depex):
        if not path.is_file() or path.is_symlink():
            raise SystemExit(f"error: missing regular source file: {path}")

    expected_t860_sdcc = "7a8104ad2d939fc61247421211f4e408b61301b3c726239119de56e86e137f8e"
    expected_mtp_sdcc = "3a47429a719b4aae1eee72fee1c352c54b50237e7de14e834efb8981dbd16e64"
    expected_shared_depex = "96d3dcd80ec35498b71c6d2f1d0e08aab0caa5c6d8b8903d3f1d469636544f1f"
    if sha256(t860_sdcc) != expected_t860_sdcc:
        raise SystemExit("error: fixed T860 SdccDxe hash mismatch")
    if sha256(mtp_sdcc) != expected_mtp_sdcc:
        raise SystemExit("error: fixed SM8150 MTP SdccDxe hash mismatch")
    if sha256(t860_depex) != expected_shared_depex or sha256(mtp_depex) != expected_shared_depex:
        raise SystemExit("error: T860 and SM8150 MTP SdccDxe dependency expressions differ")

    before = {
        str(path.relative_to(root)): sha256(path)
        for path in (source, inf, t860_sdcc, mtp_sdcc, t860_depex, mtp_depex)
    }
    data = source.read_bytes()
    eol = b"\r\n" if b"\r\n" in data else b"\n"

    data = replace_once(
        data,
        b'#include "MsBootPolicy.h"' + eol + eol + b"#define USB_DRIVE_SECOND_CHANCE_DELAY_S",
        b'#include "MsBootPolicy.h"'
        + eol
        + b"#include <Protocol/BlockIo.h>"
        + eol
        + b"#include <Protocol/LoadedImage.h>"
        + eol
        + b"#include <Library/IoLib.h>"
        + eol
        + eol
        + b"#define USB_DRIVE_SECOND_CHANCE_DELAY_S",
        "BlockIo and read-only MMIO includes",
    )

    data = replace_once(
        data,
        b"static BOOT_SEQUENCE  mSddBootSequence[] = {"
        + eol
        + b"  MsBootHDD,"
        + eol
        + b"  MsBootDone"
        + eol
        + b"};",
        b"static BOOT_SEQUENCE  mSddBootSequence[] = {"
        + eol
        + b"  MsBootSD,"
        + eol
        + b"  MsBootDone"
        + eol
        + b"};",
        "SDD boot sequence",
    )

    ipv6_tail = (
        b"  return CheckDeviceNode (DevicePath, MESSAGING_DEVICE_PATH, MSG_IPv6_DP);"
        + eol
        + b"}"
        + eol
        + eol
        + b"BOOLEAN EFIAPI"
        + eol
        + b"FilterOnlyUSB ("
    )
    sd_filter = eol.join(
        (
            b"  return CheckDeviceNode (DevicePath, MESSAGING_DEVICE_PATH, MSG_IPv6_DP);",
            b"}",
            b"",
            b"STATIC",
            b"BOOLEAN",
            b"FileSystemHasSdMarker (",
            b"  EFI_HANDLE  Handle",
            b"  )",
            b"{",
            b"  EFI_SIMPLE_FILE_SYSTEM_PROTOCOL  *FileSystem;",
            b"  EFI_FILE_PROTOCOL                *Root;",
            b"  EFI_FILE_PROTOCOL                *Marker;",
            b"  EFI_STATUS                       Status;",
            b"",
            b"  Root   = NULL;",
            b"  Marker = NULL;",
            b"  Status = gBS->HandleProtocol (",
            b"                  Handle,",
            b"                  &gEfiSimpleFileSystemProtocolGuid,",
            b"                  (VOID **)&FileSystem",
            b"                  );",
            b"  if (EFI_ERROR (Status)) {",
            b"    return FALSE;",
            b"  }",
            b"",
            b"  Status = FileSystem->OpenVolume (FileSystem, &Root);",
            b"  if (EFI_ERROR (Status) || (Root == NULL)) {",
            b"    return FALSE;",
            b"  }",
            b"",
            b"  Status = Root->Open (",
            b"                   Root,",
            b"                   &Marker,",
            b"                   L\"\\\\startup.nsh\",",
            b"                   EFI_FILE_MODE_READ,",
            b"                   0",
            b"                   );",
            b"  if (Marker != NULL) {",
            b"    Marker->Close (Marker);",
            b"  }",
            b"",
            b"  Root->Close (Root);",
            b"  return !EFI_ERROR (Status);",
            b"}",
            b"",
            b"STATIC",
            b"UINT64",
            b"BlockIoSizeMiB (",
            b"  EFI_BLOCK_IO_PROTOCOL  *BlockIo",
            b"  )",
            b"{",
            b"  if ((BlockIo == NULL) || (BlockIo->Media == NULL)) {",
            b"    return 0;",
            b"  }",
            b"",
            b"  return MultU64x32 (BlockIo->Media->LastBlock + 1, BlockIo->Media->BlockSize) / (1024 * 1024);",
            b"}",
            b"",
            b"STATIC",
            b"VOID",
            b"PrintHandleDevicePath (",
            b"  EFI_HANDLE  Handle",
            b"  )",
            b"{",
            b"  CHAR16  *Text;",
            b"",
            b"  Text = ConvertDevicePathToText (DevicePathFromHandle (Handle), TRUE, TRUE);",
            b"  if (Text == NULL) {",
            b"    Print (L\"    device-path: unavailable\\r\\n\");",
            b"    return;",
            b"  }",
            b"",
            b"  Print (L\"    %s\\r\\n\", Text);",
            b"  FreePool (Text);",
            b"}",
            b"",
            b"STATIC EFI_GUID  mSdccImageGuid = {",
            b"  0xF10F76DB, 0x42C1, 0x533F, { 0x34, 0xA8, 0x69, 0xBE, 0x24, 0x65, 0x31, 0x10 }",
            b"};",
            b"STATIC EFI_GUID  mSdccClockDependencyGuid = {",
            b"  0x241AFAE6, 0x885F, 0x4F6C, { 0xA7, 0xEA, 0xC2, 0x8E, 0xAB, 0x79, 0xC3, 0xE5 }",
            b"};",
            b"STATIC EFI_GUID  mSdccSecondDependencyGuid = {",
            b"  0x26BACCB3, 0x6F42, 0x11D4, { 0xBC, 0xE7, 0x00, 0x80, 0xC7, 0x3C, 0x88, 0x81 }",
            b"};",
            b"STATIC EFI_GUID  mSdDetectEventGroupGuid = {",
            b"  0xB7972C36, 0x8A4C, 0x4A56, { 0x8B, 0x02, 0x11, 0x59, 0xB5, 0x2D, 0x4B, 0xFB }",
            b"};",
            b"STATIC EFI_GUID  mPmicVregProtocolGuid = {",
            b"  0x22D38D3D, 0xE8B6, 0x4F8F, { 0x9C, 0x26, 0xBC, 0xEB, 0x07, 0xD6, 0xCB, 0x68 }",
            b"};",
            b"",
            b"// The pinned 2412.74 QcomPkg omits the public PMIC VREG header.  Keep the",
            b"// fixed Qualcomm protocol ABI local so no unreviewed package is imported.",
            b"#define T860_PM_LDO_6  5",
            b"#define T860_PM_LDO_9  8",
            b"",
            b"typedef struct {",
            b"  UINT32   PullDown;",
            b"  UINT32   SwMode;",
            b"  UINT32   PinCtrled;",
            b"  UINT32   SwEnable;",
            b"  BOOLEAN  VregOk;",
            b"} T860_PM_VREG_STATUS;",
            b"",
            b"typedef EFI_STATUS (EFIAPI *T860_PM_VREG_CONTROL)(UINT32, UINT32, BOOLEAN);",
            b"typedef EFI_STATUS (EFIAPI *T860_PM_VREG_SET_LEVEL)(UINT32, UINT32, UINT32);",
            b"typedef EFI_STATUS (EFIAPI *T860_PM_VREG_GET_LEVEL)(UINT32, UINT32, UINT32 *);",
            b"typedef EFI_STATUS (EFIAPI *T860_PM_VREG_SET_PWR_MODE)(UINT32, UINT32, UINT32);",
            b"typedef EFI_STATUS (EFIAPI *T860_PM_VREG_MULTIPHASE_CTRL)(UINT32, UINT32, UINT32);",
            b"typedef EFI_STATUS (EFIAPI *T860_PM_VREG_GET_STATUS)(UINT32, UINT32, T860_PM_VREG_STATUS *);",
            b"typedef EFI_STATUS (EFIAPI *T860_PM_VREG_SET_LEVEL_UV)(UINT32, UINT32, UINT32);",
            b"",
            b"typedef struct {",
            b"  UINT64                         Revision;",
            b"  T860_PM_VREG_CONTROL           VregControl;",
            b"  T860_PM_VREG_SET_LEVEL         VregSetLevel;",
            b"  T860_PM_VREG_GET_LEVEL         VregGetLevel;",
            b"  T860_PM_VREG_SET_PWR_MODE      VregSetPwrMode;",
            b"  T860_PM_VREG_MULTIPHASE_CTRL   VregMultiphaseCtrl;",
            b"  T860_PM_VREG_GET_STATUS        VregGetStatus;",
            b"  T860_PM_VREG_SET_LEVEL_UV      VregSetLevelUv;",
            b"} T860_QCOM_PMIC_VREG_PROTOCOL;",
            b"",
            b"STATIC",
            b"BOOLEAN",
            b"LoadedImageIsSdcc (",
            b"  EFI_LOADED_IMAGE_PROTOCOL  *LoadedImage",
            b"  )",
            b"{",
            b"  EFI_DEVICE_PATH_PROTOCOL  *Node;",
            b"",
            b"  if ((LoadedImage == NULL) || (LoadedImage->FilePath == NULL)) {",
            b"    return FALSE;",
            b"  }",
            b"",
            b"  Node = LoadedImage->FilePath;",
            b"  while (!IsDevicePathEnd (Node)) {",
            b"    if ((DevicePathType (Node) == MEDIA_DEVICE_PATH) &&",
            b"        (DevicePathSubType (Node) == MEDIA_PIWG_FW_FILE_DP) &&",
            b"        CompareGuid (",
            b"          &((MEDIA_FW_VOL_FILEPATH_DEVICE_PATH *)Node)->FvFileName,",
            b"          &mSdccImageGuid",
            b"          ))",
            b"    {",
            b"      return TRUE;",
            b"    }",
            b"",
            b"    Node = NextDevicePathNode (Node);",
            b"  }",
            b"",
            b"  return FALSE;",
            b"}",
            b"",
            b"STATIC",
            b"VOID",
            b"DiagnoseSdccDispatch (",
            b"  VOID",
            b"  )",
            b"{",
            b"  EFI_STATUS                 ClockStatus;",
            b"  EFI_STATUS                 SecondStatus;",
            b"  EFI_STATUS                 Status;",
            b"  EFI_HANDLE                 *Handles;",
            b"  EFI_LOADED_IMAGE_PROTOCOL  *LoadedImage;",
            b"  VOID                       *Interface;",
            b"  UINTN                      HandleCount;",
            b"  UINTN                      Index;",
            b"  UINTN                      SdccCount;",
            b"",
            b"  Interface   = NULL;",
            b"  ClockStatus = gBS->LocateProtocol (",
            b"                        &mSdccClockDependencyGuid,",
            b"                        NULL,",
            b"                        &Interface",
            b"                        );",
            b"  Interface    = NULL;",
            b"  SecondStatus = gBS->LocateProtocol (",
            b"                        &mSdccSecondDependencyGuid,",
            b"                        NULL,",
            b"                        &Interface",
            b"                        );",
            b"",
            b"  Handles     = NULL;",
            b"  HandleCount = 0;",
            b"  SdccCount   = 0;",
            b"  Status = gBS->LocateHandleBuffer (",
            b"                  ByProtocol,",
            b"                  &gEfiLoadedImageProtocolGuid,",
            b"                  NULL,",
            b"                  &HandleCount,",
            b"                  &Handles",
            b"                  );",
            b"  if (!EFI_ERROR (Status) && (Handles != NULL)) {",
            b"    for (Index = 0; Index < HandleCount; Index++) {",
            b"      Status = gBS->HandleProtocol (",
            b"                      Handles[Index],",
            b"                      &gEfiLoadedImageProtocolGuid,",
            b"                      (VOID **)&LoadedImage",
            b"                      );",
            b"      if (!EFI_ERROR (Status) && LoadedImageIsSdcc (LoadedImage)) {",
            b"        SdccCount++;",
            b"      }",
            b"    }",
            b"",
            b"    FreePool (Handles);",
            b"  }",
            b"",
            b"  Print (L\"Sdcc dispatch: loaded=%u images=%u\\r\\n\", SdccCount, HandleCount);",
            b"  Print (L\"Sdcc depex: clock=%r second=%r\\r\\n\", ClockStatus, SecondStatus);",
            b"}",
            b"",
            b"STATIC",
            b"VOID",
            b"PrintSdRailStatus (",
            b"  T860_QCOM_PMIC_VREG_PROTOCOL  *Vreg,",
            b"  UINT32                         VregId,",
            b"  CONST CHAR16                   *Name",
            b"  )",
            b"{",
            b"  T860_PM_VREG_STATUS  RailStatus;",
            b"  EFI_STATUS           LevelStatus;",
            b"  EFI_STATUS           Status;",
            b"  UINT32               LevelUv;",
            b"",
            b"  ZeroMem (&RailStatus, sizeof (RailStatus));",
            b"  LevelUv    = 0;",
            b"  Status      = Vreg->VregGetStatus (2, VregId, &RailStatus);",
            b"  LevelStatus = Vreg->VregGetLevel (2, VregId, &LevelUv);",
            b"  Print (",
            b"    L\" PMIC_C %s: status=%r level=%r/%u uV enabled=%d ok=%d\\r\\n\",",
            b"    Name,",
            b"    Status,",
            b"    LevelStatus,",
            b"    LevelUv,",
            b"    RailStatus.SwEnable,",
            b"    RailStatus.VregOk",
            b"    );",
            b"}",
            b"",
            b"STATIC",
            b"EFI_STATUS",
            b"EnableT860SdRails (",
            b"  VOID",
            b"  )",
            b"{",
            b"  T860_QCOM_PMIC_VREG_PROTOCOL  *Vreg;",
            b"  EFI_STATUS                    Status;",
            b"",
            b"  Vreg   = NULL;",
            b"  Status = gBS->LocateProtocol (",
            b"                  &mPmicVregProtocolGuid,",
            b"                  NULL,",
            b"                  (VOID **)&Vreg",
            b"                  );",
            b"  Print (L\"PMIC VREG protocol: %r revision=%lx\\r\\n\", Status, (Vreg == NULL) ? 0 : Vreg->Revision);",
            b"  if (EFI_ERROR (Status) || (Vreg == NULL)) {",
            b"    return Status;",
            b"  }",
            b"",
            b"  Print (L\"SD rails before enable:\\r\\n\");",
            b"  PrintSdRailStatus (Vreg, T860_PM_LDO_9, L\"L9/VDD\");",
            b"  PrintSdRailStatus (Vreg, T860_PM_LDO_6, L\"L6/VDD_IO\");",
            b"",
            b"  Status = Vreg->VregSetLevel (2, T860_PM_LDO_9, 2960);",
            b"  Print (L\"Set PMIC_C L9 to 2960mV: %r\\r\\n\", Status);",
            b"  if (EFI_ERROR (Status)) {",
            b"    return Status;",
            b"  }",
            b"",
            b"  Status = Vreg->VregSetLevel (2, T860_PM_LDO_6, 2960);",
            b"  Print (L\"Set PMIC_C L6 to 2960mV: %r\\r\\n\", Status);",
            b"  if (EFI_ERROR (Status)) {",
            b"    return Status;",
            b"  }",
            b"",
            b"  Status = Vreg->VregControl (2, T860_PM_LDO_9, TRUE);",
            b"  Print (L\"Enable PMIC_C L9/VDD: %r\\r\\n\", Status);",
            b"  if (EFI_ERROR (Status)) {",
            b"    return Status;",
            b"  }",
            b"",
            b"  gBS->Stall (1000);",
            b"  Status = Vreg->VregControl (2, T860_PM_LDO_6, TRUE);",
            b"  Print (L\"Enable PMIC_C L6/VDD_IO: %r\\r\\n\", Status);",
            b"  if (EFI_ERROR (Status)) {",
            b"    return Status;",
            b"  }",
            b"",
            b"  gBS->Stall (5000);",
            b"  Print (L\"SD rails after enable:\\r\\n\");",
            b"  PrintSdRailStatus (Vreg, T860_PM_LDO_9, L\"L9/VDD\");",
            b"  PrintSdRailStatus (Vreg, T860_PM_LDO_6, L\"L6/VDD_IO\");",
            b"  return EFI_SUCCESS;",
            b"}",
            b"",
            b"STATIC",
            b"EFI_STATUS",
            b"SignalSdCardDetectionAndConnect (",
            b"  VOID",
            b"  )",
            b"{",
            b"  EFI_STATUS  Status;",
            b"  EFI_STATUS  ConnectStatus;",
            b"  EFI_HANDLE  *Handles;",
            b"  UINTN       HandleCount;",
            b"  UINTN       Index;",
            b"  UINTN       ConnectFailures;",
            b"",
            b"  // Qualcomm PlatformBdsLib signals this event before ConnectAllDrivers.",
            b"  // Without it, event-based SdccDxe never publishes the removable BlockIO.",
            b"  Status = EfiEventGroupSignal (&mSdDetectEventGroupGuid);",
            b"  Print (L\"SD detect event: %r\\r\\n\", Status);",
            b"  if (EFI_ERROR (Status)) {",
            b"    return Status;",
            b"  }",
            b"",
            b"  Handles         = NULL;",
            b"  HandleCount     = 0;",
            b"  ConnectFailures = 0;",
            b"  Status = gBS->LocateHandleBuffer (",
            b"                  AllHandles,",
            b"                  NULL,",
            b"                  NULL,",
            b"                  &HandleCount,",
            b"                  &Handles",
            b"                  );",
            b"  if (EFI_ERROR (Status)) {",
            b"    Print (L\"Post-event handle enumeration: %r\\r\\n\", Status);",
            b"    return Status;",
            b"  }",
            b"",
            b"  for (Index = 0; Index < HandleCount; Index++) {",
            b"    ConnectStatus = gBS->ConnectController (Handles[Index], NULL, NULL, TRUE);",
            b"    if (EFI_ERROR (ConnectStatus) && (ConnectStatus != EFI_NOT_FOUND)) {",
            b"      ConnectFailures++;",
            b"    }",
            b"  }",
            b"",
            b"  FreePool (Handles);",
            b"  Print (",
            b"    L\"Post-event connect-all: handles=%u failures=%u\\r\\n\",",
            b"    HandleCount,",
            b"    ConnectFailures",
            b"    );",
            b"  return EFI_SUCCESS;",
            b"}",
            b"",
            b"STATIC",
            b"VOID",
            b"DiagnoseSdcc2Hardware (",
            b"  VOID",
            b"  )",
            b"{",
            b"  UINT32  CardDetectCtl;",
            b"  UINT32  CardDetectIo;",
            b"  UINT32  ClockAppsCbcr;",
            b"  UINT32  ClockAhbCbcr;",
            b"  UINT32  ClockCmdRcgr;",
            b"  UINT32  ClockCfgRcgr;",
            b"  UINT32  PresentState;",
            b"  UINT32  HostPower;",
            b"  UINT32  ClockReset;",
            b"  UINT32  InterruptStatus;",
            b"  UINT32  Capabilities0;",
            b"  UINT32  Capabilities1;",
            b"  UINT16  HostVersion;",
            b"",
            b"  // SM-T860 Android DTS: SDHCI2=0x08804000 and active-low card detect=TLMM GPIO96.",
            b"  // These are read-only diagnostics. No GPIO, clock, regulator, or controller register is written.",
            b"  CardDetectCtl  = MmioRead32 (0x03960000);",
            b"  CardDetectIo   = MmioRead32 (0x03960004);",
            b"  ClockAppsCbcr  = MmioRead32 (0x00114004);",
            b"  ClockAhbCbcr   = MmioRead32 (0x00114008);",
            b"  ClockCmdRcgr   = MmioRead32 (0x0011400C);",
            b"  ClockCfgRcgr   = MmioRead32 (0x00114010);",
            b"  PresentState   = MmioRead32 (0x08804024);",
            b"  HostPower      = MmioRead32 (0x08804028);",
            b"  ClockReset     = MmioRead32 (0x0880402C);",
            b"  InterruptStatus = MmioRead32 (0x08804030);",
            b"  Capabilities0  = MmioRead32 (0x08804040);",
            b"  Capabilities1  = MmioRead32 (0x08804044);",
            b"  HostVersion    = MmioRead16 (0x088040FE);",
            b"",
            b"  Print (L\"SDCC2 read-only register diagnostic:\\r\\n\");",
            b"  Print (",
            b"    L\" GPIO96 CTL=%08x IO=%08x inserted(active-low)=%d\\r\\n\",",
            b"    CardDetectCtl,",
            b"    CardDetectIo,",
            b"    ((CardDetectIo & BIT0) == 0)",
            b"    );",
            b"  Print (",
            b"    L\" GCC apps=%08x ahb=%08x cmd=%08x cfg=%08x\\r\\n\",",
            b"    ClockAppsCbcr,",
            b"    ClockAhbCbcr,",
            b"    ClockCmdRcgr,",
            b"    ClockCfgRcgr",
            b"    );",
            b"  Print (",
            b"    L\" SDHCI present=%08x host/pwr=%08x clk/rst=%08x int=%08x\\r\\n\",",
            b"    PresentState,",
            b"    HostPower,",
            b"    ClockReset,",
            b"    InterruptStatus",
            b"    );",
            b"  Print (",
            b"    L\" SDHCI caps=%08x/%08x version=%04x\\r\\n\",",
            b"    Capabilities0,",
            b"    Capabilities1,",
            b"    HostVersion",
            b"    );",
            b"}",
            b"",
            b"STATIC",
            b"VOID",
            b"DiagnoseStorageHandles (",
            b"  VOID",
            b"  )",
            b"{",
            b"  EFI_STATUS             Status;",
            b"  EFI_HANDLE             *Handles;",
            b"  EFI_BLOCK_IO_PROTOCOL  *BlockIo;",
            b"  UINTN                  HandleCount;",
            b"  UINTN                  Index;",
            b"  UINTN                  CandidateCount;",
            b"  UINT64                 SizeMiB;",
            b"  BOOLEAN                Marker;",
            b"",
            b"  Handles     = NULL;",
            b"  HandleCount = 0;",
            b"  Status = gBS->LocateHandleBuffer (",
            b"                  ByProtocol,",
            b"                  &gEfiSimpleFileSystemProtocolGuid,",
            b"                  NULL,",
            b"                  &HandleCount,",
            b"                  &Handles",
            b"                  );",
            b"  Print (L\"SimpleFS: %u handle(s), status=%r\\r\\n\", HandleCount, Status);",
            b"  if (Handles != NULL) {",
            b"    for (Index = 0; Index < HandleCount; Index++) {",
            b"      Marker = FileSystemHasSdMarker (Handles[Index]);",
            b"      Status = gBS->HandleProtocol (",
            b"                      Handles[Index],",
            b"                      &gEfiBlockIoProtocolGuid,",
            b"                      (VOID **)&BlockIo",
            b"                      );",
            b"      if (EFI_ERROR (Status) || (BlockIo->Media == NULL)) {",
            b"        Print (L\" SFS%u marker=%d BlockIO=none\\r\\n\", Index, Marker);",
            b"        continue;",
            b"      }",
            b"",
            b"      Print (",
            b"        L\" SFS%u marker=%d media=%d rem=%d logical=%d size=%LuMiB\\r\\n\",",
            b"        Index,",
            b"        Marker,",
            b"        BlockIo->Media->MediaPresent,",
            b"        BlockIo->Media->RemovableMedia,",
            b"        BlockIo->Media->LogicalPartition,",
            b"        BlockIoSizeMiB (BlockIo)",
            b"        );",
            b"    }",
            b"",
            b"    FreePool (Handles);",
            b"  }",
            b"",
            b"  Handles        = NULL;",
            b"  HandleCount    = 0;",
            b"  CandidateCount = 0;",
            b"  Status = gBS->LocateHandleBuffer (",
            b"                  ByProtocol,",
            b"                  &gEfiBlockIoProtocolGuid,",
            b"                  NULL,",
            b"                  &HandleCount,",
            b"                  &Handles",
            b"                  );",
            b"  if (Handles != NULL) {",
            b"    for (Index = 0; Index < HandleCount; Index++) {",
            b"      Status = gBS->HandleProtocol (",
            b"                      Handles[Index],",
            b"                      &gEfiBlockIoProtocolGuid,",
            b"                      (VOID **)&BlockIo",
            b"                      );",
            b"      if (EFI_ERROR (Status) || (BlockIo->Media == NULL) || !BlockIo->Media->MediaPresent) {",
            b"        continue;",
            b"      }",
            b"",
            b"      SizeMiB = BlockIoSizeMiB (BlockIo);",
            b"      if (BlockIo->Media->RemovableMedia || ((SizeMiB >= 24000) && (SizeMiB <= 40000))) {",
            b"        CandidateCount++;",
            b"      }",
            b"    }",
            b"  }",
            b"",
            b"  Print (L\"BlockIO: %u total, %u removable/24-40GiB candidate(s)\\r\\n\", HandleCount, CandidateCount);",
            b"  if (Handles != NULL) {",
            b"    for (Index = 0; Index < HandleCount; Index++) {",
            b"      Status = gBS->HandleProtocol (",
            b"                      Handles[Index],",
            b"                      &gEfiBlockIoProtocolGuid,",
            b"                      (VOID **)&BlockIo",
            b"                      );",
            b"      if (EFI_ERROR (Status) || (BlockIo->Media == NULL) || !BlockIo->Media->MediaPresent) {",
            b"        continue;",
            b"      }",
            b"",
            b"      SizeMiB = BlockIoSizeMiB (BlockIo);",
            b"      if (!BlockIo->Media->RemovableMedia && ((SizeMiB < 24000) || (SizeMiB > 40000))) {",
            b"        continue;",
            b"      }",
            b"",
            b"      Print (",
            b"        L\" BIO%u rem=%d logical=%d block=%u size=%LuMiB\\r\\n\",",
            b"        Index,",
            b"        BlockIo->Media->RemovableMedia,",
            b"        BlockIo->Media->LogicalPartition,",
            b"        BlockIo->Media->BlockSize,",
            b"        SizeMiB",
            b"        );",
            b"      PrintHandleDevicePath (Handles[Index]);",
            b"    }",
            b"",
            b"    FreePool (Handles);",
            b"  }",
            b"}",
            b"",
            b"STATIC",
            b"VOID",
            b"FilterMarkedFileSystems (",
            b"  EFI_HANDLE  *HandleBuffer,",
            b"  UINTN       *HandleCount",
            b"  )",
            b"{",
            b"  UINTN  Index;",
            b"",
            b"  for (Index = 0; Index < *HandleCount;) {",
            b"    if (!FileSystemHasSdMarker (HandleBuffer[Index])) {",
            b"      (*HandleCount)--;",
            b"      CopyMem (",
            b"        &HandleBuffer[Index],",
            b"        &HandleBuffer[Index + 1],",
            b"        (*HandleCount - Index) * sizeof (EFI_HANDLE)",
            b"        );",
            b"      continue;",
            b"    }",
            b"",
            b"    Index++;",
            b"  }",
            b"}",
            b"",
            b"BOOLEAN EFIAPI",
            b"FilterOnlySD (",
            b"  EFI_DEVICE_PATH_PROTOCOL  *DevicePath",
            b"  )",
            b"{",
            b"  return (DevicePath != NULL);",
            b"}",
            b"",
            b"BOOLEAN EFIAPI",
            b"FilterOnlyUSB (",
        )
    )
    data = replace_once(data, ipv6_tail, sd_filter, "SD device-path filter")

    data = replace_once(
        data,
        b"  FilterHandles (Handles, &HandleCount, ByFilter);" + eol,
        eol.join(
            (
                b"  if (ByFilter == FilterOnlySD) {",
                b"    Print (L\"\\r\\nT860 SD probe: %u SimpleFS handle(s)\\r\\n\", HandleCount);",
                b"    FilterMarkedFileSystems (Handles, &HandleCount);",
                b"    Print (L\"T860 SD probe: %u startup.nsh marker(s)\\r\\n\", HandleCount);",
                b"  } else {",
                b"    FilterHandles (Handles, &HandleCount, ByFilter);",
                b"  }",
            )
        ) + eol,
        "marker-aware filesystem filtering",
    )

    hdd_case = b"      case MsBootHDD:" + eol
    sd_case = eol.join(
        (
            b"      case MsBootSD:",
            b"        GraphicStatus = SetGraphicsConsoleMode (GCM_NATIVE_RES);",
            b"        if (EFI_ERROR (GraphicStatus) != FALSE) {",
            b'          DEBUG ((DEBUG_ERROR, "%a Unable to set console mode - %r\\n", __FUNCTION__, GraphicStatus));',
            b"        }",
            b"",
            b"        Print (L\"\\r\\nT860 SDCC VREG + EVENT DIAGNOSTIC\\r\\n\");",
            b"        Print (L\"Looking for \\\\startup.nsh; internal UFS fallback is disabled.\\r\\n\");",
            b"        DiagnoseSdccDispatch ();",
            b"        Status = EnableT860SdRails ();",
            b"        if (!EFI_ERROR (Status)) {",
            b"          Status = SignalSdCardDetectionAndConnect ();",
            b"        } else {",
            b"          Print (L\"SD event skipped because rail setup failed: %r\\r\\n\", Status);",
            b"        }",
            b"        DiagnoseSdcc2Hardware ();",
            b"        DiagnoseStorageHandles ();",
            b"        Status = SelectAndBootDevice (&gEfiSimpleFileSystemProtocolGuid, FilterOnlySD);",
            b"        Print (L\"\\r\\nSD boot did not transfer control: %r\\r\\n\", Status);",
            b"        Print (L\"Diagnostic stopped. Hold Power + Volume Down to reboot.\\r\\n\");",
            b"        while (TRUE) {",
            b"          gBS->Stall (1000 * 1000);",
            b"        }",
            b"      case MsBootHDD:",
        )
    ) + eol
    data = replace_once(data, hdd_case, sd_case, "SD boot case")
    source.write_bytes(data)

    inf_data = inf.read_bytes()
    inf_eol = b"\r\n" if b"\r\n" in inf_data else b"\n"
    inf_data = replace_once(
        inf_data,
        b"[LibraryClasses]" + inf_eol + b"  DevicePathLib",
        b"[LibraryClasses]"
        + inf_eol
        + b"  IoLib"
        + inf_eol
        + b"  DevicePathLib",
        "IoLib dependency",
    )
    inf_data = replace_once(
        inf_data,
        b"[Protocols]" + inf_eol + b"  gEfiSimpleFileSystemProtocolGuid",
        b"[Protocols]"
        + inf_eol
        + b"  gEfiBlockIoProtocolGuid"
        + inf_eol
        + b"  gEfiLoadedImageProtocolGuid"
        + inf_eol
        + b"  gEfiSimpleFileSystemProtocolGuid",
        "BlockIo protocol dependency",
    )
    inf.write_bytes(inf_data)

    after = {
        str(path.relative_to(root)): sha256(path)
        for path in (source, inf, t860_sdcc, mtp_sdcc, t860_depex, mtp_depex)
    }
    if sha256(t860_sdcc) != expected_t860_sdcc:
        raise SystemExit("error: native T860 SdccDxe changed during event-only diagnostic")
    report = {
        "schema": 1,
        "profile": "project-aloha-2412.74-sdcc-vreg-event-diagnostic",
        "purpose": "enable the T860 SD card rails PM8150L L9 and L6 at 2.96V, use the native T860 SdccDxe, signal Qualcomm's fixed external-SD event group, enumerate storage, then boot only a root startup.nsh volume",
        "sd_power": {
            "pmic_index": 2,
            "pmic_name": "PMIC_C / PM8150L",
            "vdd": {"resource": "LDO9", "millivolts": 2960},
            "vdd_io_initial": {"resource": "LDO6", "millivolts": 2960},
            "source": "SM-T860 Android DTS uses pm8150l_l9 for vdd and pm8150l_l6 for vdd-io; SD initialization begins at 3V signaling",
        },
        "external_sd_event": {
            "guid": "b7972c36-8a4c-4a56-8b02-1159b52d4bfb",
            "reference_repository": "https://github.com/SwedMlite/BOOT.XF.3.3",
            "reference_commit": "55ff7c1920ccf084951b2770d46ffcbe8917864f",
            "reference_driver_path": "QcomPkg/Drivers/SdccDxe/SdccDxe.c",
            "reference_bds_path": "QcomPkg/Library/PlatformBdsLib/PlatformBdsLib.c",
        },
        "sdcc_depex": {
            "expression": "241afae6-885f-4f6c-a7ea-c28eab79c3e5 AND 26baccb3-6f42-11d4-bce7-0080c73c8881",
            "clock_protocol_guid": "241afae6-885f-4f6c-a7ea-c28eab79c3e5",
            "second_protocol_guid": "26baccb3-6f42-11d4-bce7-0080c73c8881",
            "driver_file_guid": "f10f76db-42c1-533f-34a8-69be24653110",
        },
        "sdcc_driver": {
            "native_path": str(t860_sdcc.relative_to(root)),
            "native_sha256": expected_t860_sdcc,
            "comparison_mtp_path": str(mtp_sdcc.relative_to(root)),
            "comparison_mtp_sha256": expected_mtp_sdcc,
            "staged_sha256": sha256(t860_sdcc),
            "shared_depex_sha256": expected_shared_depex,
            "replacement_performed": False,
        },
        "mmio_reads": {
            "gcc_sdcc2": ["0x00114004", "0x00114008", "0x0011400c", "0x00114010"],
            "sdhci2": [
                "0x08804024",
                "0x08804028",
                "0x0880402c",
                "0x08804030",
                "0x08804040",
                "0x08804044",
                "0x088040fe",
            ],
            "tlmm_gpio96": ["0x03960000", "0x03960004"],
        },
        "diagnostic_patch_mmio_writes": [],
        "runtime_side_effects": {
            "native_driver_controller_state_changes_possible": True,
            "removable_media_reads_possible": True,
            "filesystem_writes_requested": False,
            "partition_writes_requested": False,
            "description": "the diagnostic explicitly enables PMIC_C LDO9/LDO6 at 2.96V, then signals Qualcomm external-SD detection; native SdccDxe may program SDCC/GCC/TLMM state and read card metadata before read-only enumeration",
        },
        "files_before": before,
        "files_after": after,
        "device_writes_performed": False,
        "deployable": False,
    }
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
